### PR TITLE
Fix input delay

### LINKED ISSUE #344: Tracking issue for controller input lag
I've been debugging input lag with switch pro controller over USB and i've found the root cause. As far as i can tell this is something that should affect both usb and bluetooth connections and all controllers. I've created yet another issue for lag as this one is nonspecific and should be easier to find while googling.

The issue is that there is a buffer built up with data to read and we're not reading fast enough. By reading hid data until there is no more data to read (thus discarding all but the latest data on each read) the controller input become responsive. I suspect that the reason that there seems to be less issues with bluetooth is that the transfer rate is slower. I'll try to create PR for this soon.

### PR DESCRIPTION
**Pull request by RobertBorg**
fixes #344 by reading (and discarding) all but the latest available HID data. it appears to be bufffered somewhere.

## TODO
- ~~[ ] Handle Timestamp for motion data better~~

### CODE REVIEW

**Comment by RobertBorg** [comment]
> 
> 
> Looks good. I'll test and merge when I find some time. What do you mean by "handle the timestamp" better for motion data?

I figured as you're basing the timestamp on a byte that is wrapping around it's possible that we'll get incorrect timestamps if we discard enough packets to get a wrap around. it's also possible there is only a surplus of data initially. Anyhow i've done some testing with motion data and it seems to be working well enough for my purposes. I only recently started meddling with Cemu so i'd love if someone tested this with a little broader scope.

**Comment by LionsAd** [comment]
I can confirm that most likely https://github.com/Davidobot/BetterJoy/pull/106 introduced the USB input lag problems.

While the fix looks good (we keep the async reading) we need to ensure that we don’t regress #106 again at the same time - but maybe the timeout reading was not needed in the first place.

Btw. @Davidobot The best controller implementation that is OSS for joycons, pro controller, DS4, etc. can be found in #chromium/chromium. Just search for Nintendo or DS4.

It’s Google typical that they rather create it in a monster code base than to provide it as a small reusable library that everyone could profit from.

Oh well - at least it is open source. I presume they use that for the Stadia Browser implementation and hence it’s quite professional including correct lighting, charging grip, etc.

**Comment by LionsAd** [comment]
Oh - for sure did not want to imply you need to rewrite anything, but sometimes it’s great if one is able to look at other implementations.

**Comment by LionsAd** [comment]
I used the test build and can confirm this fixes the input delay for pro controller via USB.

**Comment by RobertBorg** [comment]
> 
> 
> @RobertBorg
> #353 > potentially related to removing the timeout setting in the hdi read?

I'm skeptical but i'll look into it. I'm working on extracting a OutputController concept from JoyCon so we don't need to have this GodClass with everything. I'm also adding diffing to ensure that we don't send updates more often than we need to. Hopefully this will allow us to process data fast enough so that we don't need to discard data any longer.

**Pull request merged**
